#!/usr/bin/env bash

# A script for creating a blog post on lexicachromatica.xyz

# Maintainer:       Ben Buchanan
# Version:          1.0.0
# Last Modified:    02-Aug-2024

POST_DIR=blog/_posts/

printf 'Please enter a title for this post: '
read -r TITLE

printf 'Please enter a meta for this post: '
read -r META

read -r -d '' BOILERPLATE << EOF
---
title: $TITLE
meta: $META
---

Blog text goes here.

<div class="attrib">
Ben Buchanan
</div>
EOF

FILENAME="$(date +"%Y-%m-%d")-${TITLE// /-}.md"

[ -f "$POST_DIR/$FILENAME" ] && {
    printf "A post with the filename '%s' already exists!\n" "$FILENAME"
    exit 1
}

printf "%s\n" "$BOILERPLATE" > "$POST_DIR/$FILENAME" && printf "Successfully created post '%s'\n" "$FILENAME"
